services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      FRONTEND_URL: "http://localhost:3000"
      DATABASE_URL: "postgresql+psycopg2://admin:admin@database:5432/kanbanai"
    depends_on:
      - database
    networks:
      - database-network
    ports:
      - "8000:8000"
    volumes:    # TODO: Remove this volume only used to faster development without re-building
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    environment:
      BACKEND_URL: "http://localhost:8000"
    networks:
      - database-network
    ports:
      - "3000:3000"
    volumes:    # TODO: Remove this volume only used to faster development without re-building
      - ./frontend:/app
    command: "npm run dev"

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kanbanai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database-network
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local

networks:
  database-network:
    driver: bridge
